// Code generated by protoc-gen-go. DO NOT EDIT.
// source: egress.proto

/*
Package logcache is a generated protocol buffer package.

It is generated from these files:
	egress.proto
	ingress.proto

It has these top-level messages:
	ReadRequest
	ReadResponse
	SendRequest
	SendResponse
*/
package logcache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import loggregator_v2 "code.cloudfoundry.org/go-loggregator/rpc/loggregator_v2"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnvelopeTypes int32

const (
	EnvelopeTypes_ANY     EnvelopeTypes = 0
	EnvelopeTypes_LOG     EnvelopeTypes = 1
	EnvelopeTypes_COUNTER EnvelopeTypes = 2
	EnvelopeTypes_GAUGE   EnvelopeTypes = 3
	EnvelopeTypes_TIMER   EnvelopeTypes = 4
	EnvelopeTypes_EVENT   EnvelopeTypes = 5
)

var EnvelopeTypes_name = map[int32]string{
	0: "ANY",
	1: "LOG",
	2: "COUNTER",
	3: "GAUGE",
	4: "TIMER",
	5: "EVENT",
}
var EnvelopeTypes_value = map[string]int32{
	"ANY":     0,
	"LOG":     1,
	"COUNTER": 2,
	"GAUGE":   3,
	"TIMER":   4,
	"EVENT":   5,
}

func (x EnvelopeTypes) String() string {
	return proto.EnumName(EnvelopeTypes_name, int32(x))
}
func (EnvelopeTypes) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ReadRequest struct {
	SourceId     string        `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	StartTime    int64         `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime      int64         `protobuf:"varint,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Limit        int64         `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	EnvelopeType EnvelopeTypes `protobuf:"varint,5,opt,name=envelope_type,json=envelopeType,enum=logcache.EnvelopeTypes" json:"envelope_type,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReadRequest) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *ReadRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ReadRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *ReadRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadRequest) GetEnvelopeType() EnvelopeTypes {
	if m != nil {
		return m.EnvelopeType
	}
	return EnvelopeTypes_ANY
}

type ReadResponse struct {
	Envelopes *loggregator_v2.EnvelopeBatch `protobuf:"bytes,1,opt,name=envelopes" json:"envelopes,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadResponse) GetEnvelopes() *loggregator_v2.EnvelopeBatch {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "logcache.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "logcache.ReadResponse")
	proto.RegisterEnum("logcache.EnvelopeTypes", EnvelopeTypes_name, EnvelopeTypes_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Egress service

type EgressClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type egressClient struct {
	cc *grpc.ClientConn
}

func NewEgressClient(cc *grpc.ClientConn) EgressClient {
	return &egressClient{cc}
}

func (c *egressClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/logcache.Egress/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Egress service

type EgressServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
}

func RegisterEgressServer(s *grpc.Server, srv EgressServer) {
	s.RegisterService(&_Egress_serviceDesc, srv)
}

func _Egress_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logcache.Egress/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Egress_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logcache.Egress",
	HandlerType: (*EgressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Egress_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egress.proto",
}

func init() { proto.RegisterFile("egress.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0xc6, 0x8d, 0x31, 0x6a, 0x46, 0x7d, 0xc9, 0xbb, 0xf4, 0x4f, 0x6a, 0x11, 0xc4, 0x93, 0xf4,
	0x90, 0x42, 0x7a, 0xe8, 0xa1, 0xbd, 0xd8, 0xb2, 0x88, 0xb4, 0x55, 0x58, 0x62, 0xa1, 0x27, 0x49,
	0x93, 0x21, 0x06, 0x34, 0x9b, 0x66, 0x57, 0xc1, 0x6f, 0xd6, 0x8f, 0x57, 0xb2, 0x5b, 0xab, 0xed,
	0xed, 0x99, 0xe7, 0xb7, 0xcc, 0x3e, 0x33, 0x03, 0x6d, 0x4c, 0x0a, 0x14, 0xc2, 0xcb, 0x0b, 0x2e,
	0x39, 0x69, 0xae, 0x78, 0x12, 0x85, 0xd1, 0x12, 0xbb, 0xff, 0xb7, 0xfe, 0x35, 0x66, 0x5b, 0x5c,
	0xf1, 0x1c, 0x35, 0x1c, 0x7c, 0x1a, 0xd0, 0x62, 0x18, 0xc6, 0x0c, 0x3f, 0x36, 0x28, 0x24, 0xb9,
	0x04, 0x5b, 0xf0, 0x4d, 0x11, 0xe1, 0x22, 0x8d, 0x5d, 0xa3, 0x6f, 0x0c, 0x6d, 0xd6, 0xd4, 0xc6,
	0x24, 0x26, 0x3d, 0x00, 0x21, 0xc3, 0x42, 0x2e, 0x64, 0xba, 0x46, 0xb7, 0xda, 0x37, 0x86, 0x26,
	0xb3, 0x95, 0x13, 0xa4, 0x6b, 0x24, 0x17, 0xd0, 0xc4, 0x2c, 0xd6, 0xd0, 0x54, 0xb0, 0x81, 0x59,
	0xac, 0xd0, 0x09, 0x58, 0xab, 0x74, 0x9d, 0x4a, 0xb7, 0xa6, 0x7c, 0x5d, 0x90, 0x7b, 0xe8, 0xec,
	0xe3, 0x2c, 0xe4, 0x2e, 0x47, 0xd7, 0xea, 0x1b, 0xc3, 0x7f, 0xfe, 0xb9, 0xb7, 0x4f, 0xec, 0xd1,
	0x6f, 0x1c, 0xec, 0x72, 0x14, 0xac, 0x8d, 0x47, 0xe5, 0xe0, 0x09, 0xda, 0x3a, 0xb9, 0xc8, 0x79,
	0x26, 0x90, 0xdc, 0x81, 0xbd, 0xe7, 0x42, 0x45, 0x6f, 0xf9, 0xbd, 0xb2, 0x53, 0x52, 0x60, 0x12,
	0x4a, 0x5e, 0x78, 0x5b, 0xff, 0xa7, 0xdf, 0x43, 0x28, 0xa3, 0x25, 0x3b, 0xbc, 0xbf, 0x9a, 0x41,
	0xe7, 0xd7, 0x5f, 0xa4, 0x01, 0xe6, 0x68, 0xfa, 0xe6, 0x54, 0x4a, 0xf1, 0x3c, 0x1b, 0x3b, 0x06,
	0x69, 0x41, 0xe3, 0x71, 0x36, 0x9f, 0x06, 0x94, 0x39, 0x55, 0x62, 0x83, 0x35, 0x1e, 0xcd, 0xc7,
	0xd4, 0x31, 0x4b, 0x19, 0x4c, 0x5e, 0x28, 0x73, 0x6a, 0xa5, 0xa4, 0xaf, 0x74, 0x1a, 0x38, 0x96,
	0x3f, 0x82, 0x3a, 0x55, 0x57, 0x20, 0xb7, 0x50, 0x2b, 0x73, 0x92, 0xd3, 0xc3, 0x58, 0x47, 0x1b,
	0xef, 0x9e, 0xfd, 0xb5, 0xf5, 0x38, 0x83, 0xca, 0x7b, 0x5d, 0x9d, 0xe8, 0xe6, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0xce, 0x62, 0x99, 0x3d, 0xcf, 0x01, 0x00, 0x00,
}
